// Only add a key after its illustrated sheet exists and has passed visual review.
// Every registered file lives at assets/motion/wearing/<cat>/<outfit>/<action>.png.
// New sheets have fine 1–2px seams; legacy unadorned sheets keep their own 6px inset.
// Example: 'bori/ribbon/pet': { inset: 2 },
// Missing combinations deliberately remain dressed, still illustrations.
export const WORN_MOTION_SHEETS = {
  'bori/ribbon/pet': { inset: 2 },
  'bori/bandana/pet': { inset: 2 },
  'bori/vest/pet': { inset: 2 },
  'bori/sailor/pet': { inset: 2 },
  'bori/ribbon/groom': { inset: 2 },
  'bori/bandana/groom': { inset: 2 },
  'bori/vest/groom': { inset: 2 },
  'bori/sailor/groom': { inset: 2 },
  'mochi/ribbon/pet': { inset: 2 },
  'mochi/bandana/pet': { inset: 2 },
  'mochi/vest/pet': { inset: 2 },
  'mochi/sailor/pet': { inset: 2 },
  'mochi/ribbon/groom': { inset: 2 },
  'mochi/bandana/groom': { inset: 2 },
  'mochi/vest/groom': { inset: 2 },
  'mochi/sailor/groom': { inset: 2 },
  'luna/ribbon/pet': { inset: 2 },
  'luna/bandana/pet': { inset: 2 },
  'luna/vest/pet': { inset: 2 },
  'luna/sailor/pet': { inset: 2 },
  'luna/ribbon/groom': { inset: 2 },
  'luna/bandana/groom': { inset: 2 },
  'luna/vest/groom': { inset: 2 },
  'luna/sailor/groom': { inset: 2 },
  'byeol/ribbon/pet': { inset: 2 },
  'byeol/bandana/pet': { inset: 2 },
  'byeol/vest/pet': { inset: 2 },
  'byeol/sailor/pet': { inset: 2 },
  'hodu/ribbon/pet': { inset: 2 },
  'hodu/bandana/pet': { inset: 2 },
  'hodu/vest/pet': { inset: 2 },
  'hodu/sailor/pet': { inset: 2 },
  'nabi/ribbon/pet': { inset: 2 },
  'nabi/bandana/pet': { inset: 2 },
  'nabi/vest/pet': { inset: 2 },
  'nabi/sailor/pet': { inset: 2 },
  'nabi/ribbon/groom': { inset: 2 },
  'nabi/bandana/groom': { inset: 2 },
  'nabi/vest/groom': { inset: 2 },
  'nabi/sailor/groom': { inset: 2 },
  'bam/ribbon/pet': { inset: 2 },
  'bam/bandana/pet': { inset: 2 },
  'bam/sailor/pet': { inset: 2 },
  'siru/ribbon/pet': { inset: 2 },
  'siru/bandana/pet': { inset: 2 },
  'siru/vest/pet': { inset: 2 },
  'siru/sailor/pet': { inset: 2 },
  'oreo/ribbon/pet': { inset: 2 },
  'oreo/bandana/pet': { inset: 2 },
  'oreo/vest/pet': { inset: 2 },
  'oreo/sailor/pet': { inset: 2 },
  'miso/ribbon/pet': { inset: 2 },
  'miso/vest/pet': { inset: 2 },
  'miso/sailor/pet': { inset: 2 },
  'bam/vest/pet': { inset: 2 },
  'miso/bandana/pet': { inset: 2 },
};
