import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';
import path from 'node:path';
let playwright;
try { playwright=await import('playwright'); } catch { playwright=await import(pathToFileURL(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs'))); }
const browser=await playwright.chromium.launch({channel:'chrome',headless:true});
const context=await browser.newContext({viewport:{width:1440,height:1100},deviceScaleFactor:1});
const page=await context.newPage();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await mkdir('output/qa',{recursive:true});
const state=()=>page.evaluate(()=>JSON.parse(window.render_game_to_text()));
const capture=async name=>{await page.evaluate(()=>document.fonts.ready);await page.screenshot({path:`output/qa/${name}.png`,fullPage:true,animations:'disabled'});};
try {
 await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
 assert.equal((await state()).selectedCat,'bori');
 assert.equal(await page.locator('.cat-strip .cat-card').count(),10);
 await capture('desktop-home');
 const before=await state();
 await page.locator('.care-actions [data-action="pet"]').click();
 assert((await state()).cat.affection>before.cat.affection);
 assert.equal((await state()).modal,'motion');
 await page.keyboard.press('Escape');
 await page.locator('.story-button').click();
 assert.equal((await state()).modal,'dialogue');
 await capture('cutscene');
 await page.locator('[data-command="dialogue-next"]').click();
 await page.locator('[data-command="dialogue-next"]').click();
 assert.equal(await page.locator('[data-choice]').count(),2);
 await page.locator('[data-choice="0"]').click();
 await capture('bori-memory');
 await page.locator('[data-command="dialogue-next"]').click();
 assert.equal((await state()).album.length,1);
 await page.locator('.scene-cat.selected').click();
 assert.equal((await state()).modal,'portrait');
 await capture('portrait');
 await page.keyboard.press('Escape');
 const inventory=(await state()).inventory.food;
 await page.locator('.care-actions [data-action="feed"]').click();
 if((await state()).modal==='motion')await page.keyboard.press('Escape');
 assert.equal((await state()).inventory.food,inventory-1);
 await page.locator('.care-actions [data-action="play"]').click();
 assert.equal((await state()).modal,'play');
 const beforeCancel=await state();
 await page.locator('[data-command="catch-toy"]').click();
 await page.keyboard.press('Escape');
 assert.equal((await state()).cat.energy,beforeCancel.cat.energy,'Cancelled play consumes no energy');
 await page.locator('.care-actions [data-action="play"]').click();
 await capture('feather-play');
 for(let i=0;i<3;i++)await page.locator('[data-command="catch-toy"]').click();
 await page.waitForFunction(()=>!document.querySelector('#modal').open);
 await page.locator('.care-actions [data-action="brush"]').click();
 assert.equal((await state()).modal,'motion');
 await page.keyboard.press('Escape');
 await page.locator('[data-action="water"]').click();
 if((await state()).modal==='motion')await page.keyboard.press('Escape');
 await page.locator('[data-action="clean"]').click();
 await page.locator('[data-action="sleep"]').click();
 if((await state()).modal==='motion')await page.keyboard.press('Escape');
 assert.equal((await state()).cat.resting,true);
 assert.match(await page.locator('[data-action="sleep"]').innerText(),/깨워주기/);
 const energy=(await state()).cat.energy;
 await page.evaluate(()=>window.advanceTime(30000));
 assert((await state()).cat.energy>energy);
 await page.locator('[data-action="sleep"]').click();
 if((await state()).modal==='motion')await page.keyboard.press('Escape');
 await page.locator('[data-action="treat"]').click();
 if((await state()).modal==='motion')await page.keyboard.press('Escape');
 await page.locator('.sidebar [data-view="shop"]').click();
 const shopBefore=await state();
 await page.locator('[data-purchase="food_pack"]').click();
 assert.equal((await state()).coins,shopBefore.coins-20);
 assert.equal((await state()).inventory.food,shopBefore.inventory.food+5);
 await capture('shop');
 await page.locator('.sidebar [data-view="album"]').click();
 assert.equal(await page.locator('.memory-card.collected').count(),1);
 await capture('album');
 await page.locator('.sidebar [data-view="journal"]').click();
 assert((await page.locator('.journal-entry').count())>1);
 await page.locator('.sidebar [data-view="cats"]').click();
 assert.equal(await page.locator('.cats-gallery .cat-card').count(),10);
 await page.locator('[data-select-cat="byeol"]').click();
 assert.equal((await state()).selectedCat,'byeol');
 const persisted=await state();
 await page.reload({waitUntil:'networkidle'});
 assert.equal((await state()).selectedCat,'byeol');
 assert.equal((await state()).coins,persisted.coins);
 assert.equal((await state()).album.length,1);
 await page.locator('[data-select-cat="bori"]').click();
 await page.setViewportSize({width:390,height:844});
 await capture('mobile-home');
 assert(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'No mobile horizontal overflow');
 await page.locator('.scene-cat.selected').click();
 await capture('mobile-portrait');
 assert(await page.locator('#modal').evaluate(el=>el.scrollWidth<=el.clientWidth),'No portrait horizontal overflow');
 await page.keyboard.press('Escape');
 assert.equal(await page.locator('.scene-cat.selected').evaluate(el=>el===document.activeElement),true,'Focus returns to the cat');
 await page.locator('.care-actions [data-action="pet"]').focus();
 await page.evaluate(()=>window.advanceTime(1000));
 assert.equal(await page.locator('.care-actions [data-action="pet"]').evaluate(el=>el===document.activeElement),true,'Focus survives updates');
 await page.locator('[data-action="sleep"]').click();
 if((await state()).modal==='motion')await page.keyboard.press('Escape');
 await page.locator('.scene-cat.selected').click();
 await page.locator('.portrait-touch').click();
 assert.equal(await page.locator('#modal #toast.visible').count(),1,'Modal refusal feedback is in the dialog top layer');
 assert.match(await page.locator('#modal #toast').innerText(),/쉬고/);
 await page.keyboard.press('Escape');
 await page.locator('[data-action="sleep"]').click();
 if((await state()).modal==='motion')await page.keyboard.press('Escape');
 for(const room of ['bedroom','terrace','living-room']){
   await page.locator(`[data-room="${room}"]`).click();
   assert.equal((await state()).room,room);
   await page.locator('.room-background').evaluate(img=>img.decode());
 }
 await page.locator('.avatar').click();
 await page.locator('[data-setting="reducedMotion"]').check();
 await page.keyboard.press('Escape');
 assert(await page.locator('html').evaluate(el=>el.classList.contains('reduced-motion')));
 const broken=await page.locator('img').evaluateAll(imgs=>imgs.filter(i=>!i.complete||i.naturalWidth===0).map(i=>i.src));
 assert.deepEqual(broken,[]);
 assert.deepEqual(errors,[]);
 await writeFile('output/qa/browser-result.json',JSON.stringify({ok:true,flows:['all-care-actions','play-and-cancel','story-choice-and-CG','album','shop','save-reload','three-rooms','desktop-mobile','keyboard-focus','modal-feedback','reduced-motion','image-integrity'],errors,final:await state()},null,2));
 console.log('PASS: browser flows including care, feather play/cancel, story choices/CG, album, shop, persistence, rooms, desktop/mobile, keyboard focus, modal feedback, no script errors.');
} finally {await browser.close();}
